//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_2_Lesson5
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbWorkers
    {
        public int Id { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string SurName { get; set; }
        public string FirstName { get; set; }
        public string Birthday { get; set; }
        public Nullable<double> Salary { get; set; }
    }
}
